#!/bin/env bash

usr_prompt=$(i3-input -P 'Mark container (press "f" to mark with function keys): ' -l 1)
STRIPPED_USR_INPUT=$(echo -n $usr_prompt | rev | cut -f1 -d"=" | rev | tr -d ' ')

if [[ $STRIPPED_USR_INPUT == "16" ]]; then
    exit 0
fi

if [[ $STRIPPED_USR_INPUT == "f" ]]; then
    usr_prompt1=$(i3-input -P 'Function key chosen, input function index: ' -l 1)
    STRIPPED_USR_INPUT1=$(echo -n $usr_prompt1 | rev | cut -f1 -d"=" | rev | tr -d ' ')

    i3-msg "mark f$STRIPPED_USR_INPUT1"
else
    i3-msg "mark $STRIPPED_USR_INPUT"
fi

exit 0
