#!/usr/bin/env bash

FOCUSED_WORKSPACE_NUM=$(i3-msg -t get_workspaces | jq -r "map(select(.focused))[0].num")
usr_input=$(i3-input -P "Swap ws with ws number: " -l 1)
STRIPPED_USR_INPUT=$(echo -n $usr_input | rev | cut -f1 -d"=" | rev | tr -d ' ')

if [[ $STRIPPED_USR_INPUT == "16" ]]; then
    exit 0
fi

# move focused workspace to buffer workspace
i3-msg "rename workspace $FOCUSED_WORKSPACE_NUM to "buffer_ws"; rename workspace $STRIPPED_USR_INPUT to $FOCUSED_WORKSPACE_NUM; rename workspace "buffer_ws" to $STRIPPED_USR_INPUT"
