#!/bin/env bash
if [[ -z $1 ]]; then
    exit 1
fi

focused_ws_fullname=$(i3-msg -t get_workspaces | jq -r "map(select(.focused))[0].name")
ws_index=$(echo $focused_ws_fullname | cut -d':' -f1)
available_indexes=$(i3-msg -t get_workspaces | jq ".[].num")

# conversion to array
available_indexes_arr+=($available_indexes)

for index in ${available_indexes_arr[*]}; do
    if [[ ${index} -eq "${1}" ]]; then
        exit 1
    fi
done

if [[ $focused_ws_fullname == *:* ]]; then
    ws_name=$(echo $focused_ws_fullname | cut -d':' -f2)
else 
    ws_name=""
fi

if [[ $ws_name == "" ]]; then
    i3-msg "rename workspace to $1"
else
    i3-msg "rename workspace to $1:$ws_name"
fi
