#!/bin/env bash

set -e

get_current_marks() {
    existing_marks=$(i3-msg -t get_marks | jq -r 'join("\n")' | grep -E '^[f]{0,1}[0-9]+$' | sort | tr "\n" '/' | head -c -1)

    if [[ ! -z $existing_marks ]]; then
        echo -n \ marks:$existing_marks\ 
    fi
}

while :
do
    read line
    block="{\"full_text\":\"$(get_current_marks)\"}"
    echo "${line/\[\{/\[$block,\{}" || exit 1
done
