#!/bin/env bash

usr_prompt=$(i3-input -P 'Mark container (press "f" to mark with function keys): ' -l 1)
USR_INPUT_KEYCODE=$(echo $usr_prompt | grep -oP "Keypress\s+\K\w+")
stripped_usr_input=$(echo -n $usr_prompt | rev | cut -f1 -d"=" | rev | tr -d ' ')

if [[ ${USR_INPUT_KEYCODE} == "66" ]]; then
    exit 0
fi

if [[ ${stripped_usr_input} =~ "f" ]]; then
    f_usr_prompt=$(i3-input -P 'Function key chosen, input function index 1-9: ' -l 1)
    stripped_f_usr_input=$(echo -n $f_usr_prompt | rev | cut -f1 -d"=" | rev | tr -d ' ')

    if (( ${stripped_f_usr_input} >= 1 && ${stripped_f_usr_input} <= 9 )); then
        i3-msg "mark f${stripped_f_usr_input}"
    else
        exit 1
    fi
elif [[ ${stripped_usr_input} =~ ^[0-9]{1}$ ]]; then
    i3-msg "mark ${stripped_usr_input}"
else
    exit 1
fi

exit 0
