#!/bin/env bash

usr_prompt=$(i3-input -P 'Mark container (press "f" to mark with function keys): ' -l 1)
STRIPPED_USR_INPUT=$(echo -n $usr_prompt | rev | cut -f1 -d"=" | rev | tr -d ' ')

if [[ $STRIPPED_USR_INPUT == "16" ]]; then
    exit 0
fi

if [[ $STRIPPED_USR_INPUT == "f" ]]; then
    usr_prompt1=$(i3-input -P 'Function key chosen, input function index 0-9: ' -l 1)
    STRIPPED_USR_INPUT1=$(echo -n $usr_prompt1 | rev | cut -f1 -d"=" | rev | tr -d ' ')

    if (( $STRIPPED_USR_INPUT1 >= 1 && $STRIPPED_USR_INPUT1 <= 9 )); then
        i3-msg "mark f$STRIPPED_USR_INPUT1"
    else
        exit 0
    fi
else
    if (( $STRIPPED_USR_INPUT >= 0 && $STRIPPED_USR_INPUT <= 9 )); then
        i3-msg "mark $STRIPPED_USR_INPUT"
    else
        exit 1
    fi
fi

exit 0
