#!/bin/env bash

if [[ -z ${1} ]]; then
    echo '$1 argument was not specified'
    exit 1
fi

CONFIGFILE=$HOME/.move_float_window.json
if [[ ! -f $CONFIGFILE ]]; then
    echo 'No config file found'
    exit 1
fi

function save_preset() {
    updated_json=$(jq ".Preset = $1" $CONFIGFILE)
    echo $updated_json | jq . > $CONFIGFILE
}

MONITOR_DIMENSIONS_FILE=$HOME/.monitor_dimensions.json
if [[ ! -f $MONITOR_DIMENSIONS_FILE ]]; then
    { read primary_max_x primary_max_y ; } < <(xdotool getdisplaygeometry | awk '{print $1 " " $2}')
    # TODO: hardcoded default values, fix later <25-11-22, modernpacifist> #
    echo "{\"primary_x\": ${primary_max_x}, \"primary_y\": ${primary_max_y}, \"secondary_x\": 2880, \"secondary_y\": 1800}" | jq . > $MONITOR_DIMENSIONS_FILE
fi

# primary monitor resolution
primary_max_x=$(grep '"primary_x"' $MONITOR_DIMENSIONS_FILE | grep -o '[[:digit:]]*')
primary_max_y=$(grep '"primary_y"' $MONITOR_DIMENSIONS_FILE | grep -o '[[:digit:]]*')

# secondary monitor resolution
secondary_max_x=$(grep '"secondary_x"' $MONITOR_DIMENSIONS_FILE | grep -o '[[:digit:]]*')
secondary_max_y=$(grep '"secondary_y"' $MONITOR_DIMENSIONS_FILE | grep -o '[[:digit:]]*')

window_border_width=$(grep -oP '(?<="WindowBorderWidth": )[^"]*' $CONFIGFILE | tr -d ',')
status_bar_width=$(grep -oP '(?<="StatusBarWidth": )[^"]*' $CONFIGFILE | tr -d ',')
status_bar_position=$(grep -oP '(?<="StatusBarPosition": ")[^"]*' $CONFIGFILE | tr -d ',')

case $status_bar_position in 
    "top") top_offset=0;;
    "bottom") top_offset=$((- $status_bar_width / 2 - 4));;
    *) echo 'Invalid value for "status_bar_position" field, can be "top" or "bottom"';;
esac

{ read window_g_x window_g_y ; } < <(xdotool getwindowfocus getwindowgeometry | grep Geometry | cut -d ":" -f2 | sed 's/ //g' | sed 's/x/ /g')

pos=${1}

if [[ $pos =~ ^preset$ ]]; then
    pos=$(jq '.Preset' $CONFIGFILE)
    # setting default
    if [[ $pos == null ]]; then
        pos=3
    fi
fi

case $pos in
    # primary left - bottom
    '1') new_pos="$(($window_border_width)) $(($primary_max_y - $window_g_y - $window_border_width + $top_offset))";;
    # primary mid - bottom
    '2') new_pos="$(($primary_max_x / 2 - $window_g_x / 2)) $(($primary_max_y - $window_g_y - $window_border_width + $top_offset))";;
    # primary right - bottom
    '3') new_pos="$(($primary_max_x - $window_g_x - $window_border_width)) $(($primary_max_y - $window_g_y - $window_border_width + $top_offset))";;
    # primary left - mid
    '4') new_pos="$(($window_border_width)) $(($primary_max_y / 2 - $window_g_y / 2 + $status_bar_width / 2))";;
    # primary mid - mid
    '5') new_pos="$(($primary_max_x / 2 - $window_g_x / 2)) $(($primary_max_y / 2 - $window_g_y / 2 + $status_bar_width / 2))";;
    # primary right - mid
    '6') new_pos="$(($primary_max_x - $window_g_x - $window_border_width)) $(($primary_max_y / 2 - $window_g_y / 2 + $status_bar_width / 2))";;
    # primary left - top
    '7') new_pos="$window_border_width $(($status_bar_width + $window_border_width + $top_offset))";;
    # primary mid - top
    '8') new_pos="$(($primary_max_x / 2 - $window_g_x / 2)) $(($status_bar_width + $window_border_width + $top_offset))";;
    # primary right - top
    '9') new_pos="$(($primary_max_x - $window_g_x - $window_border_width)) $(($status_bar_width + $window_border_width + $top_offset))";;

    # secondary left - top
    '10') new_pos="$(($primary_max_x + $window_border_width)) $(($status_bar_width + $window_border_width + $top_offset))";;
    # secondary left - mid
    '11') new_pos="$(($primary_max_x + $window_border_width)) $(($secondary_max_y / 2 - $window_g_y / 2 - $window_border_width + $top_offset))";;
    # secondary left - bottom
    '12') new_pos="$(($primary_max_x + $window_border_width)) $(($secondary_max_y - $window_g_y - $window_border_width + $top_offset))";;
    # secondary mid - top
    '13') new_pos="$(($primary_max_x + $secondary_max_x / 2 - $window_g_x / 2 - $window_border_width)) $(($status_bar_width + $window_border_width + $top_offset))";;
    # secondary mid - mid
    '14') new_pos="$(($primary_max_x + $secondary_max_x / 2 - $window_g_x / 2 - $window_border_width)) $(($secondary_max_y / 2 - $window_g_y / 2 - $window_border_width + $top_offset))";;
    # secondary mid - bottom
    '15') new_pos="$(($primary_max_x + $secondary_max_x / 2 - $window_g_x / 2 - $window_border_width)) $(($secondary_max_y - $window_g_y - $window_border_width + $top_offset))";;
    # secondary right - top
    '16') new_pos="$(($primary_max_x + $secondary_max_x - $window_g_x - $window_border_width)) $(($status_bar_width + $window_border_width + $top_offset))";;
    # secondary right - mid
    '17') new_pos="$(($primary_max_x + $secondary_max_x - $window_g_x - $window_border_width)) $(($secondary_max_y / 2 - $window_g_y / 2 - $window_border_width + $top_offset))";;
    # secondary right - bottom
    '18') new_pos="$(($primary_max_x + $secondary_max_x - $window_g_x - $window_border_width)) $(($secondary_max_y - $window_g_y - $window_border_width + $top_offset))";;

    *) echo 'Invalid value in $1 argument, must be 1-12' >&2; exit 2;;
esac

if [[ $2 =~ ^save$ ]]; then
    save_preset $pos
fi

xdotool windowmove $(xdotool getactivewindow) $new_pos
