#!/bin/env bash

if [[ -z $1 ]]; then
    exit 1
fi

monitor1_abs_pos_x=3840
monitor1_abs_pos_y=0
monitor1_size_x=914
monitor1_size_y=1028

monitor2_abs_pos_x=3840
monitor2_abs_pos_y=1028
monitor2_size_x=914
monitor2_size_y=772

monitor3_abs_pos_x=5154
monitor3_abs_pos_y=0
monitor3_size_x=1566
monitor3_size_y=1800

if [[ ${1} =~ ^mark$ ]]; then
    f_usr_prompt=$(i3-input -P 'Monitor scratchpad mark mode chosen, input monitor index 1-9: ' -l 1)
    stripped_m_usr_input=$(echo -n $f_usr_prompt | rev | cut -f1 -d"=" | rev | tr -d ' ')

    if (( ${stripped_m_usr_input} == 1 )); then
        i3-msg "mark monitor1, move scratchpad, move absolute position ${monitor1_abs_pos_x} ${monitor1_abs_pos_y}, resize set ${monitor1_size_x} ${monitor1_size_y}"
        exit 0
    fi

    if (( ${stripped_m_usr_input} == 2 )); then
        i3-msg "mark monitor2, move scratchpad, move absolute position ${monitor2_abs_pos_x} ${monitor2_abs_pos_y}, resize set ${monitor2_size_x} ${monitor2_size_y}"
        exit 0
    fi

    if (( ${stripped_m_usr_input} == 3 )); then
        i3-msg "mark monitor3, move scratchpad, move absolute position ${monitor3_abs_pos_x} ${monitor3_abs_pos_y}, resize set ${monitor3_size_x} ${monitor3_size_y}"
        exit 0
    fi

    if (( ${stripped_m_usr_input} >= 4 && ${stripped_m_usr_input} <= 9 )); then
        i3-msg "mark monitor${stripped_m_usr_input}, move scratchpad"
    else
        exit 1
    fi
fi

if [[ ${1} =~ ^show$ ]]; then
    i3-msg "[con_mark=\"^monitor1$\"] focus, move absolute position ${monitor1_abs_pos_x} ${monitor1_abs_pos_y}, resize set ${monitor1_size_x} ${monitor1_size_y}"
    i3-msg "[con_mark=\"^monitor2$\"] focus, move absolute position ${monitor2_abs_pos_x} ${monitor2_abs_pos_y}, resize set ${monitor2_size_x} ${monitor2_size_y}"
    i3-msg "[con_mark=\"^monitor3$\"] focus, move absolute position ${monitor3_abs_pos_x} ${monitor3_abs_pos_y}, resize set ${monitor3_size_x} ${monitor3_size_y}"
fi

if [[ ${1} =~ ^hide$ ]]; then
    i3-msg '[con_mark="^monitor[0-9]$"] move scratchpad'
fi
