#!/bin/bash

FOCUSED_WORKSPACE=$(i3-msg -t get_workspaces | jq -r "map(select(.focused))[0].num")
usr_input=$(i3-input -P "Append title: ")
STRIPPED_USR_INPUT=$(echo -n $usr_input | rev | cut -f1 -d"=" | rev | tr -d ' ')

# exit if user presses escape
if [[ $STRIPPED_USR_INPUT == "16" ]]; then
    exit 0
fi

if [[ $STRIPPED_USR_INPUT == "" ]]; then
    i3-msg "rename workspace to "${FOCUSED_WORKSPACE}""
else 
    i3-msg "rename workspace to "${FOCUSED_WORKSPACE}:${STRIPPED_USR_INPUT}""
fi
