#!/bin/env bash

file_loc="$HOME/.monitor_dimensions.json"

# for now screen2 will be primary
read -a screens_resolutions <<< $(xrandr | grep -w 'connected' | grep -wEo '[0-9]{4}x[0-9]{4}' | awk '{print}' ORS=' ')

res="{"
counter=1
for s in ${screens_resolutions[@]}; do
    { read x  y ; } < <(echo $s | awk -F'x' '{print $1 " " $2}')
    res+="\"screen${counter}\":$x, \"screen$(($counter+1))\":$y,"
    counter=$(($counter+2))
done

res="${res%?}"
res+="}"

echo $res | jq . > $file_loc
