#!/bin/env bash

if [[ -z $1 ]]; then
    echo '$1 $2 arguments were not specified'
    exit 1
fi

MONITOR_DIMENSIONS_FILE=$HOME/.monitor_dimensions.json
if [[ -f $MONITOR_DIMENSIONS_FILE ]]; then
    primary_max_x=$(grep '"primary_x"' $MONITOR_DIMENSIONS_FILE | grep -o '[[:digit:]]*')
    primary_max_y=$(grep '"primary_y"' $MONITOR_DIMENSIONS_FILE | grep -o '[[:digit:]]*')
fi

CONFIGFILE=$HOME/.scale_float_window.json
if [[ ! -f $CONFIGFILE ]]; then
    echo 'No config file found'
    exit 1
fi

function update_window_size() {
    updated_list=$(jq ".Windows | map(if .id == $1 then .window_size_y |= $2 else . end)" $CONFIGFILE)
    jq ".Windows |= $updated_list" $CONFIGFILE | jq . > temp.json && mv temp.json $CONFIGFILE
}

function update_window_flag() {
    updated_list=$(jq ".Windows | map(if .id == $focused_window_id then .resized_flag |= $1 else . end)" $CONFIGFILE)
    jq ".Windows |= $updated_list" $CONFIGFILE | jq . > temp.json && mv temp.json $CONFIGFILE
}

function resize_vertically_top() {
    window_g_y_config=$(jq ".Windows[] | select(.id == $3) | .window_size_y" $CONFIGFILE)
    vertical_diff=$(( $window_size_y - $window_g_y_config ))

    case $2 in
        0) update_window_size $focused_window_id $window_size_y && i3-msg "resize grow height $1 px or $1 ppt, move container up $1" && update_window_flag 1;;
        1) i3-msg "resize shrink height $vertical_diff px or $vertical_diff ppt, move container down $vertical_diff" && update_window_flag 0;;
    esac
}

function resize_vertically_down() {
    window_g_y_config=$(jq ".Windows[] | select(.id == $3) | .window_size_y" $CONFIGFILE)
    vertical_diff=$(( $window_size_y - $window_g_y_config ))

    case $2 in
        0) update_window_size $focused_window_id $window_size_y && i3-msg "resize grow height $1 px or $1 ppt" && update_window_flag 1;;
        1) i3-msg "resize shrink height $vertical_diff px or $vertical_diff ppt" && update_window_flag 0;;
    esac
}

{ read window_size_x window_size_y ; } < <(xdotool getwindowfocus getwindowgeometry | grep Geometry | grep -o '[[:digit:]]*' | xargs)
{ read window_pos_x window_pos_y ; } < <(xdotool getwindowfocus getwindowgeometry | grep Position | grep -o '[[:digit:]]*' | xargs | awk '{print $1,$2}')

focused_window_id=$(xdotool getwindowfocus)
resized_flag=0

# 2104 - max size
if (( $window_size_y == 2104 )); then
    resized_flag=1
fi

result=$(jq ".Windows[] | select(.id == $focused_window_id)" $CONFIGFILE)

# if value does not exist, add it to the JSON list
if [[ -z $result ]]; then
    new_val="{\"id\": $focused_window_id, \"resized_flag\": $resized_flag, \"window_size_y\": $window_size_y}"
    jq ".Windows += [$new_val]" $CONFIGFILE > temp.json && mv temp.json $CONFIGFILE
fi

window_border_width=$(grep '"WindowBorderWidth"' $CONFIGFILE | grep -o '[[:digit:]]*')
status_bar_width=$(grep '"StatusBarWidth"' $CONFIGFILE | grep -o '[[:digit:]]*')
flag_resized=$(jq ".Windows[] | select(.id == $focused_window_id) | .resized_flag" $CONFIGFILE)

resize_value=$(( $primary_max_y - $window_size_y - $status_bar_width - $(($window_border_width * 2)) ))

case $1 in
    'w') resize_vertically_top $resize_value $flag_resized $focused_window_id;;
    's') resize_vertically_down $resize_value $flag_resized $focused_window_id;;

    '1') i3-msg "resize shrink width $2 px or $2 ppt, move container right $2 px";;
    # restoring the flag if window was resized vertically
    '2') i3-msg "resize grow height $2 px or $2 ppt, move container up $2 px" && update_window_flag 0;;
    '3') i3-msg "resize shrink height $2 px or $2 ppt, move container down $2 px" && update_window_flag 0;;
    '4') i3-msg "resize grow width $2 px or $2 ppt, move container left $2 px";;

    '5') i3-msg "resize shrink width $2 px or $2 ppt";;
    '6') i3-msg "resize grow height $2 px or $2 ppt" && update_window_flag 0;;
    '7') i3-msg "resize shrink height $2 px or $2 ppt" && update_window_flag 0;;
    '8') i3-msg "resize grow width $2 px or $2 ppt";;
esac
