#!/usr/bin/env bash

FOCUSED_WORKSPACE_NAME=$(i3-msg -t get_workspaces | jq -r "map(select(.focused))[0].name")
usr_input=$(i3-input -P "Swap ws with ws number: " -l 1)
USR_INPUT_KEYCODE=$(echo $usr_input | grep -oP "Keypress\s+\K\w+")

if [[ ${USR_INPUT_KEYCODE} == "66" ]]; then
    exit 0
fi

STRIPPED_USR_INPUT=$(echo -n $usr_input | rev | cut -f1 -d"=" | rev | tr -d ' ')

# if workspace does not exist then exit
WS_TO_SWAP_NAME=$(i3-msg -t get_workspaces | jq "map(select(.num==${STRIPPED_USR_INPUT}))[0] | .name")
if [[ ${WS_TO_SWAP_NAME} == "null" ]]; then
    notify-send -i $HOME/Pictures/warning.png -u low -t 5000 -- "You can't swap workspace that does not exist"
    exit 0
fi

# move focused workspace to buffer workspace
i3-msg "rename workspace $FOCUSED_WORKSPACE_NAME to "buffer_ws""
i3-msg "rename workspace $WS_TO_SWAP_NAME to $FOCUSED_WORKSPACE_NAME"
i3-msg "rename workspace "buffer_ws" to $WS_TO_SWAP_NAME"

# TODO: swap workspaces on different monitors <19-07-22, modernpacifist> #
