#!/bin/env bash

if [[ -z $1 ]]; then
    echo 'No sound value was specified'
    exit 1
fi

CURRENT_VOLUME=$(amixer -D pulse sget Master | grep 'Left:' | awk -F'[][]' '{ print $2 }' | tr -d '%')

if [[ $1 == "toggle" ]]; then
    pactl set-sink-mute @DEFAULT_SINK@ toggle && notify-send --expire-time=500 '__volume_control: toggled'
    exit 0
fi

# round to the closest 10
if [[ $1 == "round" ]]; then
    if [ $((CURRENT_VOLUME % 10)) -eq 0 ]; then
        exit 0
    fi

    rounded_volume=$((($CURRENT_VOLUME + 5)/10 * 10))
    pactl set-sink-volume @DEFAULT_SINK@ ${rounded_volume}% && notify-send --expire-time=1500 "__volume_control: rounded to ${rounded_volume}"
    exit 0
fi

if [[ ! $1 =~ ^[\+\-]{1}[0-9]{1,}$ ]]; then
    echo '$1 argument does not match format'
    exit 1
fi

stripped_usr_input=$(echo $1 | tr -d '\+\-')

MAX_VOLUME=$2
if [[ -z $2 ]]; then
    MAX_VOLUME=100
fi

usr_input_sign=${1:0:1}
wanted_volume_value=$(($CURRENT_VOLUME $usr_input_sign $stripped_usr_input))

if (( $wanted_volume_value > $MAX_VOLUME )); then
    echo 'Wanted volume value exceeds max volume value'
    pactl set-sink-volume @DEFAULT_SINK@ ${MAX_VOLUME}%
    exit 0
fi

pactl set-sink-volume @DEFAULT_SINK@ ${1}% && notify-send --expire-time=1500 "__volume_control: ${1}%"

exit 0
